[project]
name = "mp6"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64", "osx-64"]
version = "6.0.1"

[dependencies]
filelock = "*"
meson = ">=1.3.1"
ninja = "*"
modflow-devtools = "*"

[tasks]

clean = { cmd = "rm -rf builddir" }
setup = { cmd = "meson setup --prefix=$(pwd) --bindir=bin builddir", env = { PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig" } }
build = "meson install -C builddir"
test = { cmd = "meson test --verbose --no-rebuild -C builddir version" }
get-ostag = { cmd = "python -c 'from modflow_devtools.ostags import get_ostag; print(get_ostag())'"}
